### ISSUE TITLE
Add HTTP proxies as environment variables into containers

### ISSUE THREAD

**Issue by docsteveharris** [UCLH-Foundry/jupyterlab-docker#1]
Something like

```yml
# docker-compose.yml
x-http-proxy: &http-proxy ${HTTP_PROXY}
x-https-proxy: &https-proxy ${HTTPS_PROXY}
x-no-proxy: &no-proxy localhost,127.0.0.1,uclvlddpragae07,uclvlddpragae08,api,web,cache,baserow

x-proxy-common: &proxy-common
  HTTP_PROXY: *http-proxy
  http_proxy: *http-proxy
  HTTPS_PROXY: *https-proxy
  https_proxy: *https-proxy
  NO_PROXY: *no-proxy
  no_proxy: *no-proxy

x-build-args-common: &build-args-common
  <<: *proxy-common
```
